spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/incidentops
    username: incidentopsuser
    password: arjun123
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    url: jdbc:postgresql://localhost:5432/incidentops
    user: incidentopsuser
    password: your_password