spring:
  application:
    name:incident-ops
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
server:
  port:8080
jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000} #Setting to 1 day currently
logging:
  level:
    root: INFO