spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5433/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

  data:
    redis:
      host: host.docker.internal
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama-3.3-70b-versatile
      embedding:
        enabled: false

    ollama:
      base-url: http://host.docker.internal:11434

    vectorstore:
      pgvector:
        initialize-schema: true

incidentops:
  ai:
    model: llama-3.3-70b-versatile
    temperature: 0.3
    max-tokens: 2048

logging:
  level:
    root: INFO